### ISSUE TITLE
关于HOTA评价类别的问题

### ISSUE THREAD

**Issue by Ribls** [JackWoo0831/Easier_To_Use_TrackEval#2]
您好，MOT新手想问一下，TrackEval中的HOTA是只能评价单个类别目标吗，如果我想像其他MOT论文中得到最终的HOTA，要怎么做呢。
![image](https://github.com/JackWoo0831/Easier_To_Use_TrackEval/assets/77656114/2371a322-d7d6-4249-b81d-d38fe64b5e2e)
类似这种结果

**Comment by JackWoo0831** [comment]
您好, 按照我的理解, HOTA MOTA确实只能评测单类目标. 如果您有多个有效的类, 那就把所有有效的类都视为一类.

**Comment by Ribls** [comment]
> 您好, 按照我的理解, HOTA MOTA确实只能评测单类目标. 如果您有多个有效的类, 那就把所有有效的类都视为一类.

明白，感谢大佬的耐心解答
